package anyhash

import (
	"encoding/hex"
	"testing"
)

// TestPHPMarshalRoundtrip tests that MarshalPHP→UnmarshalPHP preserves hash state.
// We hash "abc", marshal, unmarshal, write "def", and verify we get hash("abcdef").
func TestPHPMarshalRoundtrip(t *testing.T) {
	// hash("abcdef") for each algorithm — generated by PHP.
	abcdefVectors := map[string]string{
		"crc32":      "b94ff5a0",
		"crc32b":     "4b8e39ef",
		"crc32c":     "53bceff1",
		"adler32":    "081e0256",
		"md4":        "804e7f1c2586e50b49ac65db5b645131",
		"md5":        "e80b5017098950fc58aad83c8c14978e",
		"sha1":       "1f8ac10f23c5b5bc1167bda84b833e5c057a77d2",
		"sha256":     "bef57ec7f53a6d40beb640a780a639c83bc29ac8a9816f1fc6c5c6dcd93c4721",
		"sha384":     "c6a4c65b227e7387b9c3e839d44869c4cfca3ef583dea64117859b808c1e3d8ae689e1e314eeef52a6ffe22681aa11f5",
		"sha512":     "e32ef19623e8ed9d267f657a81944b3d07adbb768518068e88435745564e8d4150a0a703be2a7d88b61e3d390c2bb97e2d4c311fdc69d6b1267f05f59aa920e7",
		"sha512/224": "236c829cfea4fd6d4de61ad15fcf34dca62342adaf9f2001c16f29b8",
		"sha512/256": "e4fdcb11d1ac14e698743acd8805174cea5ddc0d312e3e47f6372032571bad84",
		"fnv132":     "9f2d4718",
		"fnv1a32":    "ff478a2a",
		"fnv164":     "24021f6539ec0bd8",
		"fnv1a64":    "d80bda3fbe244a0a",
		"joaat":      "0161526f",
	}

	for algo, wantFinal := range abcdefVectors {
		t.Run(algo, func(t *testing.T) {
			// Hash "abc"
			h, err := New(algo)
			if err != nil {
				t.Fatal(err)
			}
			h.Write([]byte("abc"))

			// Marshal
			name, state, buf, err := MarshalPHP(h)
			if err != nil {
				t.Fatalf("MarshalPHP: %v", err)
			}

			// Unmarshal into fresh hash
			h2, err := UnmarshalPHP(name, state, buf)
			if err != nil {
				t.Fatalf("UnmarshalPHP: %v", err)
			}

			// Write "def" and check final hash
			h2.Write([]byte("def"))
			got := hex.EncodeToString(h2.Sum(nil))
			if got != wantFinal {
				t.Errorf("after marshal/unmarshal: got %s, want %s", got, wantFinal)
			}
		})
	}
}
