package anyhash

import (
	"encoding/hex"
	"fmt"
	"strings"
	"testing"
)

// TestPHPMarshalRoundtrip tests that MarshalPHP→UnmarshalPHP preserves hash state.
// We hash "abc", marshal, unmarshal, write "def", and verify we get hash("abcdef").
func TestPHPMarshalRoundtrip(t *testing.T) {
	// hash("abcdef") for each algorithm — generated by PHP.
	abcdefVectors := map[string]string{
		"crc32":      "b94ff5a0",
		"crc32b":     "4b8e39ef",
		"crc32c":     "53bceff1",
		"adler32":    "081e0256",
		"md4":        "804e7f1c2586e50b49ac65db5b645131",
		"md5":        "e80b5017098950fc58aad83c8c14978e",
		"sha1":       "1f8ac10f23c5b5bc1167bda84b833e5c057a77d2",
		"sha256":     "bef57ec7f53a6d40beb640a780a639c83bc29ac8a9816f1fc6c5c6dcd93c4721",
		"sha384":     "c6a4c65b227e7387b9c3e839d44869c4cfca3ef583dea64117859b808c1e3d8ae689e1e314eeef52a6ffe22681aa11f5",
		"sha512":     "e32ef19623e8ed9d267f657a81944b3d07adbb768518068e88435745564e8d4150a0a703be2a7d88b61e3d390c2bb97e2d4c311fdc69d6b1267f05f59aa920e7",
		"sha512/224": "236c829cfea4fd6d4de61ad15fcf34dca62342adaf9f2001c16f29b8",
		"sha512/256": "e4fdcb11d1ac14e698743acd8805174cea5ddc0d312e3e47f6372032571bad84",
		"fnv132":     "9f2d4718",
		"fnv1a32":    "ff478a2a",
		"fnv164":     "24021f6539ec0bd8",
		"fnv1a64":    "d80bda3fbe244a0a",
		"joaat":      "0161526f",
		// remaining algorithms — PHP-generated vectors
		"md2":        "ad8b6e280214c5da745cacca55f91db3",
		"ripemd128":  "6a20234ae8734e683c790f7cd81cfbed",
		"ripemd160":  "0ec97ff209a8c019df8f4027d7aea8f9c45ac0cf",
		"ripemd256":  "c81b268daf6e489dd8c8bb05c1e8b54f7756ba8d3a3ce8b0588cb74f964a6967",
		"ripemd320":  "f7f89749a7d08f0381271ae9ba6a39b0d9b4aef0aec46f6cbc92dd07c56ab58c87c03b5959d46ffa",
		"whirlpool":  "a73e425459567308ba5f9eb2ae23570d0d0575eb1357ecf6ac88d4e0358b0ac3ea2371261f5d4c070211784b525911b9eec0ad968429bb7c7891d341cff4e811",
		"tiger128,3": "9895d378382b1e93a4a2f5ccd425453f",
		"tiger160,3": "9895d378382b1e93a4a2f5ccd425453f01ddbab2",
		"tiger192,3": "9895d378382b1e93a4a2f5ccd425453f01ddbab2137ce35e",
		"tiger128,4": "5e19baf89eb80634c31e796feda50b27",
		"tiger160,4": "5e19baf89eb80634c31e796feda50b2706b7952f",
		"tiger192,4": "5e19baf89eb80634c31e796feda50b2706b7952fd89a144b",
		"snefru":     "038fcef9b494b91d6f86e2fd39cb30d94871637a33d10034f7c7f54ea214da37",
		"snefru256":  "038fcef9b494b91d6f86e2fd39cb30d94871637a33d10034f7c7f54ea214da37",
		"gost":       "12fb4bf9bd7fd6899a9b577092bebeb176007a178229628ad90fad241baddbf4",
		"gost-crypto": "b68a46325b6dd736d5543d29fe3f56db77c003c471d7cbe4d85dc8401fca439c",
		"haval128,3": "4af0c84626a2c1e6baa99eea75e82746",
		"haval160,3": "4fff5769eb7dbefef996fb3a2063d189693060f1",
		"haval192,3": "56931d71e8c883e4c8872899da27c50aaff29fe6bf678902",
		"haval224,3": "81cf9f46fe1ad2076a0fd2e5a8841dbb910b3d568e5367457cc82b79",
		"haval256,3": "e4a9eedc3121ef40ec446e5f4173b6b4f5f5c296322dbe0c5c65aa62af60e5f2",
		"haval128,4": "7d308dbc484b366ab1dae2a1dae9c9e5",
		"haval160,4": "b24425f181be278e06f5a2ef74bea0da22088490",
		"haval192,4": "d3c81d3f7b8ca3254505c443af11ef3a38352265a20c5aba",
		"haval224,4": "19f8e7ccf85689bd527eb2403148bcda92919129a60ca24b445b9510",
		"haval256,4": "8a5154d899fdb281316dc630cbe04eaa649253206f6a2028c5d2ec6dad293bbd",
		"haval128,5": "b96cc1096ea2ca6e67c8847f51f33dba",
		"haval160,5": "065f29af8d774e9799107717d3186f2918b94d3d",
		"haval192,5": "76794b090c60a0f17faeb2c43aafed4e2f8198a375cab8b5",
		"haval224,5": "3215f1ea8f8c27d6143d7816e3ba4d2fcda67c676ad2de861a79b110",
		"haval256,5": "ddd8102d73e20b791f4fa15269adad2ac11a84ed02fd02c0913b10380e6f4329",
		"murmur3a":   "6181c085",
		"murmur3c":   "e17cb90aa1af2721a9bedff9a9bedff9",
		"murmur3f":   "e47d86bfaca3bf55b07109993321845c",
		"xxh32":      "8b7cd587",
		"xxh64":      "fa8afd82c423144d",
		"sha3-224":   "ceb3f4cd85af081120bf69ecf76bf61232bd5d810866f0eca3c8907d",
		"sha3-256":   "59890c1d183aa279505750422e6384ccb1499c793872d6f31bb3bcaa4bc9f5a5",
		"sha3-384":   "d77460b0ce6109168480e279a81af32facb689ab96e22623f0122ff3a10ead263db6607f83876a843d3264dc2a863805",
		"sha3-512":   "01309a45c57cd7faef9ee6bb95fed29e5e2e0312af12a95fffeee340e5e5948b4652d26ae4b75976a53cc1612141af6e24df36517a61f46a1a05f59cf667046a",
	}

	for algo, wantFinal := range abcdefVectors {
		t.Run(algo, func(t *testing.T) {
			// Hash "abc"
			h, err := New(algo)
			if err != nil {
				t.Fatal(err)
			}
			h.Write([]byte("abc"))

			// Marshal
			name, state, err := MarshalPHP(h)
			if err != nil {
				t.Fatalf("MarshalPHP: %v", err)
			}

			// Unmarshal into fresh hash
			h2, err := UnmarshalPHP(name, state)
			if err != nil {
				t.Fatalf("UnmarshalPHP: %v", err)
			}

			// Write "def" and check final hash
			h2.Write([]byte("def"))
			got := hex.EncodeToString(h2.Sum(nil))
			if got != wantFinal {
				t.Errorf("after marshal/unmarshal: got %s, want %s", got, wantFinal)
			}
		})
	}
}

// TestPHPCrossValidation verifies that Go's MarshalPHP produces the exact same
// int32 state values as PHP's serialize(). Data generated by PHP 8.4 after
// hashing "Hello, World!" (13 bytes), then continuing with " Goodbye!" to
// verify the state is correct.
func TestPHPCrossValidation(t *testing.T) {
	type phpVector struct {
		ints  string // comma-separated int32 values from PHP
		bufs  string // hex-encoded buffer(s) from PHP, semicolon-separated
		final string // hash after appending " Goodbye!"
	}

	vectors := map[string]phpVector{
		"adler32":    {ints: "530449514", final: "56250774"},
		"crc32":     {ints: "421986592", final: "eb14701d"},
		"crc32b":    {ints: "330644527", final: "50711e3f"},
		"crc32c":    {ints: "-1297420393", final: "1c817d85"},
		"fnv132":    {ints: "1116842118", final: "c30f94fc"},
		"fnv1a32":   {ints: "1525479220", final: "d15f3eda"},
		"fnv164":    {ints: "331434118,2069800133", final: "debcb7df93c95f9c"},
		"fnv1a64":   {ints: "-863667116,1861245911", final: "bac1a70b347f1a9a"},
		"joaat":     {ints: "-1159597642", final: "9058b737"},
		"md4":       {ints: "1732584193,-271733879,-1732584194,271733878,104,0", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "926f0849eae953ac003313e427614305"},
		"md5":       {ints: "13,0,1732584193,-271733879,-1732584194,271733878,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "35c2561cff27f77bef684a83e38df351"},
		"sha1":      {ints: "1732584193,-271733879,-1732584194,271733878,-1009589776,104,0", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "bd3c9ad9022ace4b35076c5ab5528eb68a239b4a"},
		"sha256":    {ints: "1779033703,-1150833019,1013904242,-1521486534,1359893119,-1694144372,528734635,1541459225,104,0", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "7f150c289656e0e3826b97d7eada6853b1fafb0e4eb4899d4891c33ea09ed886"},
		"ripemd128": {ints: "1732584193,-271733879,-1732584194,271733878,104,0", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "29a26b0d9d91cc44671c1aa6e27cdb23"},
		"ripemd160": {ints: "1732584193,-271733879,-1732584194,271733878,-1009589776,104,0", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "68ba0b910410e34e46bfcac53fc6160ae958bca9"},
		"tiger192,3": {ints: "-1985229329,19088743,1985229328,-19088744,-1011687033,-258562636,0,0,13", bufs: "48656c6c6f2c20576f726c6421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "f2658f03e3b385f78912d355896ff25bc324442f91886498"},
		"gost":      {ints: "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,104,0,13", bufs: "48656c6c6f2c20576f726c642100000000000000000000000000000000000000", final: "e494b9251d748e428fa74ea845b0296c05c73d0e6b243040f697ccce6a80fc74"},
		"snefru256": {ints: "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,104,13", bufs: "48656c6c6f2c20576f726c642100000000000000000000000000000000000000", final: "dea1c7782eaf31b3f9918dc95f4ddfd68907859b62187852608c24c4375b4884"},
		"haval256,3": {ints: "608135816,-2052912941,320440878,57701188,-1542899678,698298832,137296536,-330404727,104,0", bufs: "48656c6c6f2c20576f726c642100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", final: "590441e5b9fc9d3843c73af19404baf39dbba516d535638318419312f9bf746d"},
		"murmur3a":  {ints: "-1174436471,553648129,13", final: "7aff6a5e"},
		"xxh32":     {ints: "13,0,606290984,-2048144777,0,1640531535,1819043144,1461726319,1684828783,33,13,0", final: "3a4792ca"},
		"xxh64":     {ints: "13,0,-1379879466,1625958382,668265295,-1028477379,0,0,2048144761,1640531534,1819043144,1461726319,1684828783,33,0,0,0,0,13,0,0,0", final: "e180bacaa412b368"},
	}

	for algo, v := range vectors {
		t.Run(algo, func(t *testing.T) {
			h, err := New(algo)
			if err != nil {
				t.Fatal(err)
			}
			h.Write([]byte("Hello, World!"))

			phpAlgo, state, err := MarshalPHP(h)
			if err != nil {
				t.Fatal(err)
			}
			_ = phpAlgo

			// Convert state elements to string representations for comparison.
			// int32 values become their decimal string, []byte values become hex-encoded strings
			// separated from int runs by semicolons.
			var goInts []string
			var goBufs []string
			for _, elem := range state {
				switch val := elem.(type) {
				case int32:
					goInts = append(goInts, fmt.Sprintf("%d", val))
				case []byte:
					goBufs = append(goBufs, hex.EncodeToString(val))
				}
			}
			gotInts := strings.Join(goInts, ",")
			if gotInts != v.ints {
				t.Errorf("int32 state mismatch\ngot  %s\nwant %s", gotInts, v.ints)
			}

			// Check buffer matches PHP (if specified)
			if v.bufs != "" {
				gotBufs := strings.Join(goBufs, ";")
				if gotBufs != v.bufs {
					t.Errorf("buffer mismatch\ngot  %s\nwant %s", gotBufs, v.bufs)
				}
			}

			// Verify roundtrip: unmarshal and continue hashing
			h2, err := UnmarshalPHP(phpAlgo, state)
			if err != nil {
				t.Fatalf("UnmarshalPHP: %v", err)
			}
			h2.Write([]byte(" Goodbye!"))
			gotFinal := hex.EncodeToString(h2.Sum(nil))
			if gotFinal != v.final {
				t.Errorf("final hash mismatch\ngot  %s\nwant %s", gotFinal, v.final)
			}
		})
	}
}

// TestSeededHashes verifies seeded hash output matches PHP.
func TestSeededHashes(t *testing.T) {
	tests := []struct {
		algo string
		seed uint64
		want string
	}{
		{"murmur3a", 42, "4e4f1e68"},
		{"murmur3c", 42, "5bcf0fbe8741bbe98741bbe98741bbe9"},
		{"murmur3f", 42, "0d85089fb3cff7d67510712b42353d30"},
		{"xxh32", 42, "0147abfe"},
		{"xxh64", 42, "13c1d910702770e6"},
		{"xxh3", 12345, "717e64eafd9a85d0"},
		{"xxh128", 12345, "80ece7f827e09e79717e64eafd9a85d0"},
	}

	for _, tc := range tests {
		t.Run(fmt.Sprintf("%s/seed=%d", tc.algo, tc.seed), func(t *testing.T) {
			h, err := New(tc.algo, Options{Seed: tc.seed})
			if err != nil {
				t.Fatal(err)
			}
			h.Write([]byte("abc"))
			got := hex.EncodeToString(h.Sum(nil))
			if got != tc.want {
				t.Errorf("got %s, want %s", got, tc.want)
			}
		})
	}
}
